version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stock-price-checker
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      target: production
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
    healthcheck:
      test: curl --fail http://localhost:${PORT}/healthz || exit 1
      interval: 40s
      timeout: 30s
      retries: 5
      start_period: 30s
