version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stock-price-checker
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    command: npm run dev
